version: '3.8'

services:
  mastra-agent-generator:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "3000:3000"  # API server
      - "7860:7860"  # Gradio interface
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
